/*
 * Problem Statement:
 * You are given an integer array coins and an integer k.
 * You can make amounts using multiples of any single coin denomination (no combinations across denominations).
 * Return the kth smallest amount that can be formed.
 */

/*
 * Approach: Binary Search on Answer + Inclusion-Exclusion Principle (PIE) (O(2^M * log(min(coins) * k)))
 * 1. Filter Redundant Coins:
 *    - If coin `A` divides coin `B` (`B % A == 0`), all multiples of `B` are already generated by `A`.
 *    - Remove all multiples to reduce the number of active coins `M <= coins.length`.
 * 2. Inclusion-Exclusion Precomputation:
 *    - For each non-empty subset of coins (represented as a bitmask `1 <= i < (1 << M)`):
 *      * Compute the Least Common Multiple (LCM) of coins in the subset.
 *      * The sign is `+1` if the number of set bits is odd, and `-1` if even.
 * 3. Binary Search:
 *    - The answer lies in the range `[1, min(coins) * k]`.
 *    - For a candidate value `mid`, the number of multiples <= `mid` generated by the coins is:
 *      count(mid) = sum(sign * (mid / LCM)) across all subsets.
 *    - If `count(mid) >= k`, search the lower half (`high = mid`); otherwise search the upper half (`low = mid + 1`).
 */

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

public class KthSmallestAmountSingleDenomination3116 {
    public long findKthSmallest(int[] coins, int k) {
        Arrays.sort(coins);
        
        // Step 1: Filter redundant multiples
        List<Integer> filtered = new ArrayList<>();
        for (int c : coins) {
            boolean keep = true;
            for (int f : filtered) {
                if (c % f == 0) {
                    keep = false;
                    break;
                }
            }
            if (keep) {
                filtered.add(c);
            }
        }

        // Step 2: Precompute LCMs and signs for all non-empty subsets
        int m = filtered.size();
        int subsetCount = (1 << m) - 1;
        long[] lcms = new long[subsetCount];
        int[] signs = new int[subsetCount];
        int idx = 0;

        for (int i = 1; i < (1 << m); i++) {
            long lcmVal = 1;
            for (int j = 0; j < m; j++) {
                if ((i & (1 << j)) != 0) {
                    long g = gcd(lcmVal, filtered.get(j));
                    lcmVal = (lcmVal / g) * filtered.get(j);
                }
            }
            lcms[idx] = lcmVal;
            signs[idx] = Integer.bitCount(i) % 2 == 1 ? 1 : -1;
            idx++;
        }

        // Step 3: Binary Search on Answer
        long low = 1;
        long high = (long) filtered.get(0) * k;

        while (low < high) {
            long mid = low + (high - low) / 2;
            long count = 0;

            for (int i = 0; i < lcms.length; i++) {
                count += signs[i] * (mid / lcms[i]);
            }

            if (count >= k) {
                high = mid;
            } else {
                low = mid + 1;
            }
        }

        return low;
    }

    private long gcd(long a, long b) {
        while (b != 0) {
            long temp = b;
            b = a % b;
            a = temp;
        }
        return a;
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter coin denominations separated by space:");
        String rawInputString = scanner.nextLine().trim();

        if (rawInputString.isEmpty()) {
            System.out.println("Kth smallest amount: 0");
            return;
        }

        String[] tokens = rawInputString.split("\\s+");
        int[] coinsParam = new int[tokens.length];
        for (int i = 0; i < tokens.length; i++) {
            coinsParam[i] = Integer.parseInt(tokens[i]);
        }

        System.out.println("Enter integer k:");
        int kParam = scanner.nextInt();

        KthSmallestAmountSingleDenomination3116 solver = new KthSmallestAmountSingleDenomination3116();
        long result = solver.findKthSmallest(coinsParam, kParam);

        System.out.println("The " + kParam + "-th smallest amount is: " + result);
        scanner.close();
    }
}
